from enum import StrEnum


class ApiRequestType(StrEnum):
    OUTGOING_TRANSACTION = "OUTGOING_TRANSACTION"
    UPDATE_CONFIG = "UPDATE_CONFIG"
    REVERSE_TRANSACTION = "REVERSE_TRANSACTION"
    UPDATE_SPEC = "UPDATE_SPEC"
    UPDATE_CONNECTION = "UPDATE_CONNECTION"
    CONNECT = "CONNECT"
    DISCONNECT = "DISCONNECT"
    RECONNECT = "RECONNECT"
