from enum import StrEnum


class ApiRequestType(StrEnum):
    OUTGOING_TRANSACTION = "OUTGOING_TRANSACTION"
    GET_CONFIG = "GET_CONFIG"
    UPDATE_CONFIG = "UPDATE_CONFIG"
    REVERSE_TRANSACTION = "REVERSE_TRANSACTION"
    GET_TRANSACTION = "GET_TRANSACTION"
    GET_TRANSACTIONS = "GET_TRANSACTIONS"
    GET_SPEC = "GET_SPEC"
    UPDATE_SPEC = "UPDATE_SPEC"
    GET_CONNECTION = "GET_CONNECTION"
    UPDATE_CONNECTION = "UPDATE_CONNECTION"
    CONNECT = "CONNECT"
    DISCONNECT = "DISCONNECT"
    RECONNECT = "RECONNECT"
