from enum import StrEnum


class ApiUrl(StrEnum):
    BASE = "http://127.0.0.1:%s"
    API = "/api"
    GET_CONNECTION = "/connection"
    GET_SPECIFICATION = "/specification"
    GET_TRANSACTIONS = "/transactions"
    GET_TRANSACTION = "/transactions/{trans_id}"
    GET_CONFIG = "/config"
    CREATE_TRANSACTION = "/transactions"
    REVERSE_TRANSACTION = "/transactions/{trans_id}/reversals"
    UPDATE_SPECIFICATION = "/specification"
    RECONNECT = "/connection/restart"
    DISCONNECT = "/connection/close"
    CONNECT = "/connection/open"
    UPDATE_CONFIG = "/config"
    SIGNAL = "/about"
    CONVERT = "/transactions/convert"
    VALIDATE_TRANSACTION = "/transactions/validate"
    DOCUMENT = "/documentation"
    CREATE_PREDEFINED_TRANSACTION = "/transactions/predefined/{trans_type}"
    SWAGGER = "/openapi"
    LIVE_LOG = "/log/live"
    RAW_LOG = "/log/raw"
    LOG = "/log"
    ECHO_TEST = "/api/transactions/predefined/echo-test"
    POSTMAN = "/postman_collection"
